# Pipeline Azure DevOps ultra-simple
trigger:
  branches:
    include:
      - main

variables:
  azureSubscription: 'SEEG-Azure-Subscription'
  webAppName: 'one-hcm-seeg-backend'

stages:
  - stage: Build
    displayName: 'Build'
    jobs:
      - job: BuildJob
        displayName: 'Build Job'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.13'
          - script: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
          - script: |
              pytest tests/ --junitxml=test-results.xml
          - task: PublishTestResults@2
            inputs:
              testResultsFiles: '**/test-results.xml'

  - stage: Deploy
    displayName: 'Deploy'
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: DeployJob
        displayName: 'Deploy Job'
        environment: 'Production'
        pool:
          vmImage: 'ubuntu-latest'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  inputs:
                    azureSubscription: '$(azureSubscription)'
                    appType: 'webApp'
                    appName: '$(webAppName)'
                    package: '$(System.DefaultWorkingDirectory)'
