"""Modify application table for PDF file storage

Revision ID: c233e3cf8f4e
Revises: a9cb9ffa6018
Create Date: 2025-09-18 15:00:19.194910

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c233e3cf8f4e'
down_revision = 'a9cb9ffa6018'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_documents', sa.Column('file_data', postgresql.BYTEA(), nullable=False))
    op.add_column('application_documents', sa.Column('file_type', sa.String(), nullable=True))
    op.alter_column('application_documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('application_documents', 'file_url')
    op.drop_column('applications', 'motivation')
    op.drop_column('applications', 'url_idee_projet')
    op.drop_column('applications', 'url_lettre_integrite')
    op.drop_column('applications', 'cover_letter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('cover_letter', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('url_lettre_integrite', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('url_idee_projet', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('motivation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('application_documents', sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('application_documents', 'file_size',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('application_documents', 'file_type')
    op.drop_column('application_documents', 'file_data')
    # ### end Alembic commands ###
